stages:
  - build
  - deploy

build: #JOB 이름
  image: gradle:8.5.0-jdk17
  stage: build
  script:
    - echo [INFO] YML Settings
    - cd ./back/munggle/src/main/resources
    - echo "$APPLICATION_YML" > "application.yml"
    - cd ../../..
    - chmod +x gradlew
    - ./gradlew clean
    - ./gradlew bootJar
  artifacts:
    paths:
      - back/munggle/build/libs/*.jar
    expire_in: 1 days
  only:
    - develop/back

deploy: #JOB 이름
  image: docker:latest
  stage: deploy
  services:
    - docker:24.0.7-dind
  before_script:
    - echo [INFO] docker deploy start!
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $DOCKER_REGISTRY_USER --password-stdin
  script:
    - chmod +x back/munggle/deploy/build-image.sh
    - docker push $CI_REGISTRY:v1.0
    - docker run --name nginx-container nginx:latest
  after_script:
    - docker logout
    - echo [INFO] docker deploy end!
  only:
    - develop/back
